### ISSUE TITLE
Wont work if you block cookies

### ISSUE THREAD

**Issue by karna41317** [Acanguven/StorageService#1]
Unfortunately, different browsers have different way handling cookies, 

Firefox and Chrome will block storage services if you block cookies and it gets even worser if you go to private mode.

**Comment by Acanguven** [comment]
Project's scope is just to handle localStorage or sessionStorage access while assuming user is in private mode. Maybe we can extend this to support storage when cookies are blocked too. It might me great contribution, but it is hard tho.
