### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ItalyPaleAle** [Acanguven/StorageService#2]
I'd like to use this for a personal project, but I am not able to because it's missing a license file. As you know, without an explicit license, code defaults to "All rights reserved", and we can't incorporate it in other projects.

**Comment by Acanguven** [comment]
Hello, feel free to use it. I just added license.

**Comment by ItalyPaleAle** [comment]
Thank you, this was quick and great :) Really appreciated

**Comment by Acanguven** [comment]
You are welcome :)
